"""initial migration

Revision ID: 61ff9bbdca6d
Revises: 969c1a0e1256
Create Date: 2026-03-04 14:09:43.796575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ff9bbdca6d'
down_revision: Union[str, Sequence[str], None] = '969c1a0e1256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('chunks_count', sa.Integer(), nullable=True))
    op.drop_column('pipelines', 'chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('chunks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pipelines', 'chunks_count')
    # ### end Alembic commands ###
