"""initial migration

Revision ID: 969c1a0e1256
Revises: 3b67fc9fb91b
Create Date: 2026-03-04 14:05:17.029723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969c1a0e1256'
down_revision: Union[str, Sequence[str], None] = '3b67fc9fb91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('chunks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'chunks')
    # ### end Alembic commands ###
