"""initial migration

Revision ID: d0dafad720e0
Revises: 6c512e854d0b
Create Date: 2026-03-05 16:14:29.841347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0dafad720e0'
down_revision: Union[str, Sequence[str], None] = '6c512e854d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('name', sa.String(), nullable=True))
    op.drop_index(op.f('ix_conversations_pipeline_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_name'), 'conversations', ['name'], unique=False)
    op.drop_constraint(op.f('conversations_pipeline_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'pipeline_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('pipeline_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('conversations_pipeline_id_fkey'), 'conversations', 'pipelines', ['pipeline_id'], ['id'])
    op.drop_index(op.f('ix_conversations_name'), table_name='conversations')
    op.create_index(op.f('ix_conversations_pipeline_id'), 'conversations', ['pipeline_id'], unique=False)
    op.drop_column('conversations', 'name')
    # ### end Alembic commands ###
